---
title: "Final numbers paper"
author: "Yannick Mulders"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    theme: united
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

df <- df <- read_rds(here::here("cleaned_data", "latest_cleaned_full_data.rds")) %>% janitor::clean_names()
chem_df  <- readxl::read_xlsx((here::here("Output", "chem_index_supplementary.xlsx"))) %>% janitor::clean_names()


####################
chem_df %>% select(chem_name_shiny,
                   cas,
                   presence,
                   production_volume) %>% 
  filter(production_volume == "-1")
####################
```

## Numbers table

here we calculate the final numbers which are required in the text

```{r numbers }

wdf <- df %>% distinct(refid) %>% count %>% mutate(variable = "total studies included")

nstudies <- as.integer(wdf$n[wdf$variable == "total studies included"])

wdf <- rbind(wdf,
             chem_df %>% select(chem_name_shiny,
                                level_of_concern,
                                presence,
                                production_volume) %>% 
               # filter(c(level_of_concern == "medium" | level_of_concern == "high") & presence == "not found" & !is.na(production_volume)) %>% 
               filter(c(level_of_concern == "medium" | level_of_concern == "high") & presence == "not found" & production_volume > 0 & production_volume != "No data available") %>% 
               count() %>% 
               mutate(variable = "chemical with hazard rating not found, with prod volume >0")
             )

wdf <- rbind(wdf,
             df %>% 
               select(country_investigated) %>% 
               separate_rows(country_investigated,
                             sep = "_") %>% 
               filter(country_investigated != "Unknown") %>% 
               unique() %>% 
               count() %>% 
               mutate(variable = "unique countries of populations")
             )


wdf <- rbind(wdf,
             df %>% 
               select(country_last_author) %>% 
               separate_rows(country_last_author,
                             sep = "_") %>% 
               unique() %>% 
               count() %>% 
               mutate(variable = "unique countries of last author")
             )

wdf <- rbind(wdf,
             df %>% 
               select(country_first_auth) %>% 
               separate_rows(country_first_auth,
                             sep = "_") %>% 
               unique() %>% 
               count() %>% 
               mutate(variable = "unique countries of first author")
             )

wdf <- rbind(wdf,
            df %>% 
              select(refid,
                     population) %>% 
              filter(population == "Mother-child pairs") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies on maternal exposure",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
            )

wdf <- rbind(wdf,
            df %>% 
              select(refid,
                     population) %>% 
              filter(population == "Father-mother-child family") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies on maternal/paternal exposure",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
)

levels(as.factor(df$gender))

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     gender) %>% 
              separate_rows(gender, sep ="_") %>% 
              filter(gender == "Mixed") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies on Mixed sex",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )
            
wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     gender) %>% 
              separate_rows(gender, sep ="_") %>% 
              filter(gender == "Male") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies on Male sex",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     gender) %>% 
              separate_rows(gender, sep ="_") %>% 
              filter(gender == "Female") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies on Female sex",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     gender) %>% 
              separate_rows(gender, sep ="_") %>% 
              filter(gender == "Unknown/Not available") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies with unknown sex",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

levels(as.factor(df$age_exp))

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     age_exp) %>% 
              separate_rows(age_exp, sep ="_") %>% 
              filter(age_exp == "Adult (18+)" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of adult exposures",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     age_health) %>% 
              separate_rows(age_health, sep ="_") %>% 
              filter(age_health == "Adult (18+)" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of adult HOM",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     age_exp) %>% 
              separate_rows(age_exp, sep ="_") %>% 
              filter(age_exp == "Older adult/Elderly" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of elderly exposures",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     age_health) %>% 
              separate_rows(age_health, sep ="_") %>% 
              filter(age_health == "Older adult/Elderly" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of elderly HOM",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     risk) %>% 
              filter(risk == "No" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies without special risk",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     risk) %>% 
              filter(risk == "Yes" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies with special risk",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

spec.exp <- as.integer(sub(" .*", "", wdf$n[wdf$variable == "number (percentage) of studies with special risk"]))

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     risk,
                     risk_compartor_group) %>% 
              filter(risk == "Yes" & 
                       risk_compartor_group == "Yes" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies with special risk and comparator group",
                     n = paste0(n, " (", round((n/spec.exp*100), 1),"%)"))
             )


levels(as.factor(df$study_design))

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     study_design) %>% 
              filter(study_design == "Case study/series"      |
                     study_design == "Cross-sectional study"  |
                     study_design == "Longitudinal study" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number observational studies")
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     study_design) %>% 
              filter(study_design == "Cross-sectional study" ) %>%
              unique() %>% 
              count() %>% 
              mutate(variable = "number Cross-sectional studies")
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     study_design) %>% 
              filter(study_design == "Longitudinal study" ) %>%
              unique() %>% 
              count() %>% 
              mutate(variable = "number Longitudinal studies")
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     study_design) %>% 
              filter(study_design != "Case study/series"      &
                     study_design != "Cross-sectional study"  &
                     study_design != "Longitudinal study" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number experimental studies")
             )

  
wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     study_design) %>% 
              filter(study_design == "Experimental study with a control/comparison group" ) %>%
              unique() %>% 
              count() %>% 
              mutate(variable = "number analytical studies")
             )


wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     year) %>% 
              filter(year > 2015 ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of studies since Jan 2016",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "PCBs" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of PCBs studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "Phthalates" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of Phthalates studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )
             
wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "Bisphenols" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of Bisphenols studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )             

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "PFAS" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of PFAS studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )    

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "PBDEs" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of PBDE studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )    

levels(as.factor(df$multiple_exposures))
             

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     multiple_exposures) %>% 
              filter(multiple_exposures == "'multiple exposures measured&rsquo; (tick if &gt;1 plastic type or chemical class, whether on the &lsquo;included&rsquo; list or not)" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of multiple exposure studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )
             
wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     class) %>% 
              filter(class == "Polymers" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number (percentage) of Polymers studies",
                     n = paste0(n, " (", round((n/nstudies*100), 1),"%)"))
             )    


sum.terms <- c("Total/Sum PCB",
               "Total/Sum PBB",
               "Total/Sum PBDE",
               "Total/Sum Di-alkyl phthalates",
               "Total/Sum PFAS",
               "Total/Sum Chemical Exposure",
               "Total/Sum Bisphenols",
               "iso-propylated triaryl phosphate esters",
               "tert-butylated triaryl phosphate esters",
               "Total/Sum POPs",
               "Total/Sum Organophosphate esters",
               "Total/Sum Hexabromocyclododecane",
               "(SCCPs) Short chain chlorinated paraffins",
               "(MCCPs) Medium chain chlorinated paraffins",
               "(LCCPs) Long chain chlorinated paraffins",
               "Phosphazene flame retardants",
               "Other (straight chain dialkyl) high molecular weight phthalates")

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      class,
                      presence) %>% 
               filter(class != "Polymers" &
                        !chem_name_shiny %in% sum.terms) %>% 
               unique() %>% 
               count() %>% mutate(variable = "number additives")
)  

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      class,
                      presence) %>% 
               filter(class == "Polymers") %>% 
               unique() %>% 
               count() %>% mutate(variable = "number polymers")
) 

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      class,
                      presence) %>% 
               filter(class != "Polymers" &
                      !chem_name_shiny %in% sum.terms &
                      presence == "found") %>% 
               unique() %>% 
               count() %>% mutate(variable = "number additives found")
)  

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      class,
                      presence) %>% 
               filter(class == "Polymers" &
                        presence == "found") %>% 
               unique() %>% 
               count() %>% 
               mutate(variable = "number polymers found")
)  

wdf <- rbind(wdf,  
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               # filter(!is.na(production_volume)) %>% 
               filter(!is.na(level_of_concern)) %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "additives in deep dive and SEM")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(!is.na(level_of_concern)) %>% 
               filter(production_volume == 0 | 
                        production_volume == -1) %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "additives with prod volumes  0 or -1")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(!is.na(level_of_concern)) %>% 
               filter(production_volume == "No data available") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "additives with no prod volumes data")
             )



wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(!is.na(level_of_concern)) %>% 
               filter(level_of_concern == "No data available") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "additives with no hazard data available")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(production_volume > 0 &
                      production_volume != "No data available") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "included SEM chems with deep dive prod volumes")
             )


wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(production_volume > 0 &
                        presence == "found" &
                        production_volume != "No data available") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "found SEM chems with deep dive prod volumes")
             )


levels(as.factor(chem_df$level_of_concern))

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               # filter(!is.na(level_of_concern)) %>% 
               filter(level_of_concern == "high" | level_of_concern == "medium" ) %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "SEM chems with hazard data available")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(presence == "found") %>% 
               filter(level_of_concern == "high" | level_of_concern == "medium" ) %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "found SEM chems with hazard data available")
             )

df %>% 
  select(refid,
         level0) %>% 
  group_by(level0) %>%
  unique() %>% 
  summarise(n = length(refid)) %>% 
  arrange(-n) %>% 
  mutate(cs = cumsum(n),
         perc = cs/max(cs)*100) %>% 
  print(n=20)



fdf <- df %>%
  filter(study_design != "Case study/series" &
         study_design != "Experimental study with a control/comparison group" &
         study_design != "Experimental study without a control/comparison group (patch testing)" 
         ) %>%
  mutate(risk_special  = replace(risk_special, risk_special == "", NA),
         risk_maternal = replace(risk_maternal, risk_maternal == "", NA),
         risk_paternal = replace(risk_paternal, risk_paternal == "", NA)
         ) %>%
  unite("risk_spec", c(risk_special, risk_maternal,risk_paternal), remove = T, na.rm = T) %>%
  separate_rows(risk_spec, 
                sep = "_"
                ) %>%
  mutate(risk_group = case_when(
    str_detect(risk_spec, "Paternal") ~ "Paternal",
    str_detect(risk_spec, "Maternal") ~ "Maternal",
    str_detect(risk_spec, "Special") ~ "Individual",
    str_detect(risk, "No") ~ "None"
  )) %>%
  unique() %>%
  mutate(risk_spec = case_when(
    str_detect(risk_spec, "ingestion") ~ "Ingestion",
    str_detect(risk_spec, "occupational") ~ "Occupational",
    str_detect(risk_spec, "other") ~ "Other (location)",
    TRUE ~ "No special risk")) %>%
  filter(risk_spec != "Ingestion" &
         risk_spec != "Occupational") %>%
  unique()

nfstudies <- length(unique(fdf$refid))

fdf %>% 
  select(refid,
         level0) %>% 
  group_by(level0) %>%
  unique() %>% 
  summarise(n = length(refid)) %>% 
  arrange(-n) %>% 
  mutate(cs = cumsum(n),
         perc = cs/max(cs)*100) %>% 
  print(n=20)


wdf <- rbind(wdf,
             fdf %>% 
               select(refid,
                      level0) %>% 
               filter(level0 == "05 Endocrine, nutritional or metabolic disorders") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "endocrine studies")
             )


edf <- df %>%
  mutate(risk_special  = replace(risk_special,  risk_special == "", NA),
         risk_maternal = replace(risk_maternal, risk_maternal == "", NA),
         risk_paternal = replace(risk_paternal, risk_paternal == "", NA)
  ) %>%
  unite("risk_spec", 
        c(risk_special, risk_maternal,risk_paternal), 
        remove = T, 
        na.rm = T) %>%
  separate_rows(risk_spec, 
                sep = "_"
  ) %>%
  mutate(risk_group = case_when(
    str_detect(risk_spec, "Paternal") ~ "Paternal",
    str_detect(risk_spec, "Maternal") ~ "Maternal",
    str_detect(risk_spec, "Special") ~ "Individual",
    str_detect(risk, "No") ~ "None"
  )) %>%
  unique() %>%
  mutate(risk_spec = case_when(
    str_detect(risk_spec, "ingestion") ~ "Ingestion",
    str_detect(risk_spec, "occupational") ~ "Occupational",
    str_detect(risk_spec, "other") ~ "Other (location)",
    TRUE ~ "No special risk")) %>%
  filter(risk_spec        == "Ingestion" |
           risk_spec      == "Occupational" |
           study_design   == "Case study/series" |
           study_design   == "Experimental study with a control/comparison group" |
           study_design   == "Experimental study without a control/comparison group (patch testing)" 
  ) %>%
  unique()


wdf <- rbind(wdf,
             edf %>% 
              select(refid,
                     class) %>% 
              filter(class == "Polymers" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of Polymers studies in non fig5 studies")
             )    

wdf <- rbind(wdf,
             edf %>% 
              select(refid,
                     class) %>% 
              filter(class == "PCBs" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of PCB studies in non fig5 studies")
             )

wdf <- rbind(wdf,
             edf %>% 
              select(refid,
                     class) %>% 
              filter(class == "Bisphenols" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of bisphenol studies in non fig5 studies")
             )

wdf <- rbind(wdf,
             edf %>% 
              select(refid,
                     class) %>% 
              filter(class == "Phthalates" ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of phthalate studies in non fig5 studies")
             )


wdf <- rbind(wdf,
             edf %>% 
              select(refid,
                     class,
                     level0) %>% 
              filter(class == "Polymers" &
                      str_detect(level0, "skin") ) %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of polymer studies in non fig5 studies in level0 skin")
             )

to_code <- function(x) {
  countrycode::countrycode(x, 
                           origin = "country.name", 
                           destination = "iso2c")
}

df_gni2 <- read.csv(here::here("Data", "country_gni.csv")) %>% 
  janitor::clean_names() %>%
  mutate(country = iconv(country, "latin1", "UTF-8",sub='')) %>% 
  mutate(code = to_code(country)) %>% 
  drop_na(code) %>% 
  mutate(economic_status = factor(economic_status, levels = c("Low income",
                                                              "Lower-middle income",
                                                              "Upper-middle income",
                                                              "High income"))) 


gni_dat <- df_gni2 %>% 
  left_join((df %>% 
               select(refid,
                      country_investigated) %>%
               separate_rows(country_investigated, 
                             sep = "_") %>%
               mutate(code = to_code(country_investigated)) %>%
               unique() %>%
               group_by(country_investigated,
                        code) %>%
               count()
             ), by = c("code" = "code")
            ) %>%
  select(!country_investigated) %>%
  mutate(n = replace_na(n, 0)) 


gni_dat %>% 
  select(country,
         economic_status,
         n) %>% 
  group_by(economic_status) %>% 
  summarize(n = sum(n)) %>% 
  arrange(-n) %>% 
  mutate(cs = cumsum(n),
         perc = cs/max(cs)*100)



wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     population) %>% 
              filter(population == "Mother-child pairs") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of studies on maternal exposure")
             )


levels(as.factor(df$study_design))

wdf <- rbind(wdf,
             df %>% 
              select(refid,
                     population,
                     study_design) %>% 
              filter(population == "Mother-child pairs" &
                       study_design == "Longitudinal study") %>% 
              unique() %>% 
              count() %>% 
              mutate(variable = "number of longi studies on maternal exposure")
             )

wdf <- rbind(wdf,
             df %>% 
               select(refid,
                      level0) %>% 
               filter(str_detect(level0, "neurodevelop")) %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "neuro studies")
             )

wdf <- rbind(wdf,
             df %>% 
               select(refid,
                      level0,
                     group,
                      age_health) %>% 
               filter((str_detect(level0, "neurodevelop") &
                         str_detect(group, "eurocog") &
                      age_health == "Older adult/Elderly" ) |
                        (str_detect(level0, "ervous syst") &
                          age_health == "Older adult/Elderly" )
                                              ) %>% 
               distinct(refid) %>% 
               count() %>%
               mutate(variable = "neuro studies elderly")
             )

wdf <- rbind(wdf,
             df %>% 
               select(refid,
                      group,
                      age_health) %>% 
               filter(str_detect(group, "ental") &
                      age_health == "Older adult/Elderly") %>% 
               unique() %>% 
               count() %>%
               mutate(variable = "neuro studies elderly")
             )

total.chem <- length(chem_df$chem_name_shiny)

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence) %>% 
               filter(presence =="not found") %>% 
               count() %>% 
               mutate(variable = "chems not found",
                      n = paste0(n, " (", round((n/total.chem*100), 1),"%)"))
             )
      

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      production_volume,
                      level_of_concern) %>% 
               filter(production_volume != "No data available" &
                        !is.na(production_volume)) %>% 
               filter(as.integer(production_volume) > 0 &
                        as.integer(production_volume) <= 200) %>% 
               filter(presence == "not found") %>% 
               count() %>% 
               mutate(variable = "low prod vol chemicals")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      class,
                      production_volume,
                      level_of_concern) %>% 
               filter(
                      production_volume == "No data available" |
                      is.na(production_volume)) %>% 
               filter(class != "Polymers" &
                      !chem_name_shiny %in% total.chem ) %>% 
               count() %>% 
               mutate(variable = "no prod data additives")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      class,
                      production_volume,
                      level_of_concern) %>% 
               filter(production_volume != "No data available" &
                        !is.na(production_volume)) %>% 
               filter(as.integer(production_volume) >= 1000) %>% 
               filter(class != "Polymers" &
                      !chem_name_shiny %in% total.chem) %>% 
               filter(presence == "not found") %>% 
               filter(level_of_concern == "high" | level_of_concern == "medium" ) %>%
               count() %>% 
               mutate(variable = "high volume, high risk,  no literature")
             )

wdf <- rbind(wdf,
             chem_df %>% 
               select(chem_name_shiny,
                      presence,
                      class,
                      production_volume,
                      level_of_concern) %>% 
               filter(production_volume != "No data available" &
                      !is.na(production_volume)) %>% 
               filter(as.integer(production_volume) >= 1000) %>% 
               filter(class != "Polymers" &
                      !chem_name_shiny %in% total.chem) %>% 
               filter(presence == "not found") %>% 
               filter(level_of_concern != "high" & level_of_concern != "medium" ) %>%
               count() %>% 
               mutate(variable = "high volume, no risk classi,  no literature")
             )


levels(as.factor(df$multiple_exposures))

singles <- df %>% 
  select(refid,
         class,
         chem_name_shiny,
         multiple_exposures) %>% 
  group_by(refid) %>% 
  distinct(class) %>% 
  count(sort = T) %>% 
  filter(n==1) %>% 
  select(refid) %>% 
  unlist()


sum.refs <- df %>% 
  select(refid, 
         chem_name_shiny) %>% 
  filter(chem_name_shiny %in% sum.terms) %>% 
  select(refid) %>% 
  unique() %>% 
  unlist()


    df1      <- df %>% select(refid,
                           chem_name_shiny) %>% 
               filter(refid %in% singles) %>% 
               group_by(refid) %>% 
               distinct(chem_name_shiny) %>% 
               count(sort = F) %>% 
               filter(n > 1) %>% 
               ungroup() %>% 
               count() %>% 
               mutate(variable = "studies on single class multiple chemicals")
             


df2 <- df %>% select(refid,
              chem_name_shiny) %>% 
               filter(refid %in% singles) %>% 
               filter(refid %in% sum.refs) %>% 
               group_by(refid) %>%
               distinct(chem_name_shiny) %>% 
               count(sort = F) %>% 
               filter(n == 1 ) %>% 
               ungroup() %>% 
               count() %>% 
               mutate(variable = "studies on single class multiple chemicals")

df3 <- data.frame(0)             
df3 <- df3 %>% 
  mutate(n        = df1$n + df2$n,
         variable = "studies on single class multiple chemicals") %>% 
  select(-X0)

wdf <- rbind(wdf, df3)
                         

wdf <- rbind(wdf,
             df %>% select(refid,
                           class,
                           multiple_exposures) %>% 
               filter(refid %in% singles) %>% 
               filter(multiple_exposures == "'multiple exposures measured&rsquo; (tick if &gt;1 plastic type or chemical class, whether on the &lsquo;included&rsquo; list or not)") %>% 
               unique() %>% 
               count() %>% 
               mutate(variable = "studies on single class + multiple exposures")
             )

wdf <- rbind(wdf,
             df %>% 
               select(refid,
                      class,
                      chem_name_shiny,
                      multiple_exposures) %>% 
               group_by(refid) %>% 
               distinct(class) %>% 
               count(sort = T) %>% 
               filter(n > 1) %>% 
               ungroup() %>% 
               count() %>% 
               mutate(variable = "studies on multiple included classes")
)



wdf <- rbind(wdf, df %>% 
               select(refid, 
                      class,
                      level0) %>% 
               filter(str_detect(class, "Phthalate")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on Phthalates")
)

wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      class,
                      level0) %>% 
               filter(str_detect(class, "Phthalate"),
                      str_detect(level0, "nutritional")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on Phthalates x endocrine")
)

wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      class,
                      level0) %>% 
               filter(str_detect(class, "Phthalate"),
                      str_detect(level0, "genitouri")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on Phthalates x genitourinary")
)


wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      class,
                      level0) %>% 
               filter(str_detect(class, "Phthalate"),
                      str_detect(level0, "neurodeve")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on Phthalates x neuro")
)

wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      class,
                      level0) %>% 
               filter(str_detect(class, "Phthalate"),
                      str_detect(level0, "regnancy")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on Phthalates x pregnancy")
)

wdf <- rbind(wdf, 
             df %>% select(refid,
                           chem_name_shiny) %>% 
               filter(str_detect(chem_name_shiny, "DINCH")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on DINCH")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           chem_name_shiny) %>% 
               filter(str_detect(chem_name_shiny, "DEHTP")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on DEHTP")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           class) %>% 
               filter(str_detect(class, "OPE")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on OPEs")
             )


wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               #filter(str_detect(chem_name_shiny, "BPA")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on bisphenols")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               filter(str_detect(chem_name_shiny, "\\(Bisphenol A\\)")) %>% 
               filter(!str_detect(chem_name_shiny, "Tetrabromo")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on bisphenol A")
             )


df %>% 
  select(refid,
         class,
         chem_name_shiny) %>%
  filter(str_detect(class, "isphenol")) %>%
  unique() %>% 
  group_by_at(vars(-chem_name_shiny)) %>%
  summarize(chem_name_shiny = paste0(chem_name_shiny, collapse = "_")) %>% 
  unique() %>% 
  filter(chem_name_shiny == "(Bisphenol A) 4-[2-(4-hydroxyphenyl)propan-2-yl]phenol") %>% 
  ungroup() %>% 
  count() %>% 
  mutate(variable = "studies on exclusively bisphenol A")
  
  
  df %>% 
  select(refid,
         class,
         chem_name_shiny) %>%
  filter(str_detect(class, "isphenol")) %>%
    distinct(chem_name_shiny)
  


wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               filter(str_detect(chem_name_shiny, "\\(Bisphenol S\\)")) %>% 
               filter(!str_detect(chem_name_shiny, "Tetrabromo")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on bisphenol S")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               filter(str_detect(chem_name_shiny, "\\(Bisphenol F\\)")) %>% 
               filter(!str_detect(chem_name_shiny, "Tetrabromo")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on bisphenol F")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               filter(str_detect(chem_name_shiny, "\\(Bisphenol AF\\)")) %>% 
               filter(!str_detect(chem_name_shiny, "Tetrabromo")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on bisphenol AF")
             )

wdf <- rbind(wdf, 
             df %>% select(refid,
                           class,
                           chem_name_shiny) %>% 
               filter(str_detect(class, "isphenol")) %>% 
               filter(!str_detect(chem_name_shiny, "\\(Bisphenol F\\)") &
                        !str_detect(chem_name_shiny, "\\(Bisphenol S\\)") &
                        !str_detect(chem_name_shiny, "\\(Bisphenol AF\\)") &
                        !str_detect(chem_name_shiny, "\\(Bisphenol A\\)")) %>% 
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on other bisphenols")
             )


wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      country_investigated) %>% 
               filter(str_detect(country_investigated, "Russia")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies on russian populations")
             )

wdf <- rbind(wdf, 
             df %>% 
               select(refid, 
                      country_first_auth,
                      country_last_author) %>% 
               filter(str_detect(country_first_auth, "Russia") |
                        str_detect(country_last_author, "Russia")) %>%
               distinct(refid) %>% 
               count() %>% 
               mutate(variable = "studies by russian authors")
             )
           
wdf %>% 
  gt::gt()

writexl::write_xlsx(wdf, here::here("Output", "Final_numbers.xlsx"))
```



``` {r}

df %>% 
  select(refid,
         chem_name_shiny) %>% 
  filter(str_detect(chem_name_shiny, "silicon"))

df %>% filter(refid == "33800362")


 test <- chem_df %>% 
               select(chem_name_shiny,
                      presence) %>% 
               filter(presence =="not found") %>% 
   unique()
 
 chem_df %>% 
               select(class,
                      chem_name_shiny,
                      presence) %>% 
               filter(presence =="not found") %>% 
               filter(!chem_name_shiny %in% sum.terms) %>%
   filter(class != "Polymers") %>% 
   unique()

write.csv(test, here("Output","test_notfound.csv"))  



pfas_df <- df %>% select(refid,
              class,
              chem_name_shiny) %>% 
  filter(class == "PFAS") %>% 
  unique() %>% 
  group_by(chem_name_shiny) %>% 
  count(sort = T)

 writexl::write_xlsx(pfas_df, here::here("Output", "pfas_numbers.xlsx"))
```

``` {r - PFAS query}
########
# Of the x PFAS in our database we found that only x% were investigated in included articles, and data pertaining to these 46 PFAS can be explored in the Plastic Health Map. Of the remaining x that appear not to have been investigated in relation to human health, x are known to be produced at ≥1000 t/year (x of these for use in food contact materials) and x don't have hazard classifications. 

#########


pf <- chem_df %>% 
  select(chem_name_shiny,
         class,
         presence) %>% 
  filter(class == "PFAS") %>% 
  count() %>% 
  mutate(variable = "total number of PFAS")


pf <- rbind(pf, (chem_df %>% 
  select(chem_name_shiny,
         class,
         presence) %>% 
  filter(class == "PFAS" &
         presence == "found") %>% 
  count() %>% 
  mutate(variable = "total number found of PFAS"))
)

tpf <- data.frame(n = paste(round(pf$n[pf$variable == "total number found of PFAS"]/pf$n[pf$variable == "total number of PFAS"] *100, 2), "%"), variable = "percentage PFAS found")

pf <- rbind(pf, tpf)

pf<- rbind(pf, (chem_df %>% 
  select(chem_name_shiny,
         class,
         presence) %>% 
  filter(class == "PFAS" &
         presence == "not found") %>% 
  count() %>% 
  mutate(variable = "total number not found of PFAS"))
)


pf <-rbind(pf, chem_df %>% 
  select(chem_name_shiny,
         class,
         presence,
         production_volume) %>% 
  filter(class == "PFAS" &
         presence == "not found"&
           production_volume > "999") %>% 
  count() %>% 
  mutate(variable = "total number not found of PFAS with production volume over 1000"))


pf <- rbind(pf, chem_df %>% 
  select(chem_name_shiny,
         class,
         presence,
         production_volume,
         sector) %>% 
  filter(class == "PFAS" &
         presence == "not found" &
         # production_volume > "999" &
         str_detect(sector, "Food-contact")) %>% 
  count() %>% 
  mutate(variable = "total number not found PFAS in food contact")
  )

levels(as.factor(chem_df$level_of_concern))

pf <- rbind(pf, chem_df %>% 
  select(chem_name_shiny,
         class,
         presence,
         production_volume,
         sector,
         level_of_concern) %>% 
  filter(class == "PFAS" &
         presence == "not found" &
         #production_volume > "999" &
         #str_detect(sector, "Food-contact") &
         (level_of_concern ==  "high" | level_of_concern ==  "medium") 
         )%>% 
  count() %>% 
  mutate(variable = "total number not found of PFAS with hazard rating"))


pf <- rbind(pf, chem_df %>% 
  select(chem_name_shiny,
         class,
         presence,
         production_volume,
         sector,
         level_of_concern) %>% 
  filter(class == "PFAS" &
         presence == "not found" &
         production_volume > "999" &
         #str_detect(sector, "Food-contact") &
         (level_of_concern ==  "high" | level_of_concern ==  "medium") 
         )%>% 
  count() %>% 
  mutate(variable = "total number not found of PFAS with hazard rating and prod vol > 1000"))

pf <- rbind(pf, chem_df %>% 
  select(chem_name_shiny,
         class,
         presence,
         production_volume,
         sector,
         level_of_concern) %>% 
  filter(class == "PFAS" &
         presence == "not found" &
         production_volume > "999" &
         #str_detect(sector, "Food-contact") &
         (level_of_concern !=  "high" & level_of_concern !=  "medium") 
         )%>% 
  count() %>% 
  mutate(variable = "total number not found of PFAS without hazard rating but prod vol > 1000"))

pf %>% gt::gt()

 writexl::write_xlsx(pf, here::here("Output", "pfas_text_numbers.xlsx"))
```


```{r}

ci <- df %>% select(#refid,
              #country_last_author,
              country_investigated) %>% 
  separate_rows(country_investigated, sep = "_") %>% 
  unique()



cla <- df %>% select(#refid,
              country_last_author) %>% 
              #country_investigated) %>% 
  separate_rows(country_last_author, sep = "_") %>% 
  unique()

ci %>% filter(!country_investigated %in% cla$country_last_author) %>% print()



total.ref <- df %>% select(refid) %>% unique() %>% count()

last.5 <- df %>% select(refid,
                           year) %>% 
  filter(year >2016) %>% 
  unique() %>% count()


str_glue("with {round(last.5$n/total.ref$n*100,1)}% ({last.5$n}/{total.ref$n})")


fdf <- df %>%
  filter(study_design != "Case study/series" &
         study_design != "Experimental study with a control/comparison group" &
         study_design != "Experimental study without a control/comparison group (patch testing)" ) %>% 
  mutate(risk_special  = replace(risk_special, risk_special == "", NA),
         risk_maternal = replace(risk_maternal, risk_maternal == "", NA),
         risk_paternal = replace(risk_paternal, risk_paternal == "", NA)
         ) %>%
  unite("risk_spec", c(risk_special, risk_maternal,risk_paternal), remove = T, na.rm = T) %>%
  separate_rows(risk_spec, sep = "_") %>%
  mutate(risk_group = case_when(
    str_detect(risk_spec, "Paternal") ~ "Paternal",
    str_detect(risk_spec, "Maternal") ~ "Maternal",
    str_detect(risk_spec, "Special") ~ "Individual",
    str_detect(risk, "No") ~ "None"
  )) %>%
  unique() %>%
  mutate(risk_spec = case_when(
    str_detect(risk_spec, "ingestion") ~ "Ingestion",
    str_detect(risk_spec, "occupational") ~ "Occupational",
    str_detect(risk_spec, "other") ~ "Other (location)",
    TRUE ~ "No special risk")) %>%
  filter(risk_spec != "Ingestion" &
         risk_spec != "Occupational") %>%
  unique()

hom_df <- fdf %>%
    select(refid,
           level0) %>%
    unique() %>%
    drop_na() %>%
    group_by(level0)%>%
    count(sort = T) %>% 
  ungroup() %>% 
  mutate(cum_n = cumsum(n),
         cum_per = str_glue("{round(cum_n/max(cum_n)*100,1)}%")
         ) %>% 
  print(n=21)
 

writexl::write_xlsx(hom_df, here::here("Output", "cumulative_HOM_numbers.xlsx"))


fdf %>%
    select(refid,
           level0,
           category) %>%
  filter(str_detect(level0,"ndocrine")) %>% 
    unique() %>%
    drop_na() %>%
    group_by(group)%>%
    count(sort = T)


```

```{r}
df %>% 
  select(refid,
         chem_name_shiny,
         class,
         year) %>% 
  mutate(subclass = ifelse(str_detect(chem_name_shiny, paste(gsub("([()])","\\\\\\1", alt_pht), collapse="|")),
         "Phthalate substitutes",
         "Traditional phthalates")) %>%
  select(!chem_name_shiny) %>% 
  filter(subclass == "Phthalate substitutes" |
         class == "Phthalates"
         ) %>% 
  unique() %>% 
  group_by(subclass)
  count()
```

